name: codeCovScan workflow

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Node 22
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 22.11.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPROXY: direct
        GONOSUMDB: "*"
        GOPRIVATE: https://github.com/Checkmarx/ # Add your private organization url here

    - name: Authenticate with GitHub package registry
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

    - name: Install dependencies 
      run: npm install 

    - name: Run tests and generate coverage 
      run: |
        npm run test --coverage
         
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # v4.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # create your CODECOV_TOKEN using the token from 'set repo' in codecov site
        files: ./cover.out  
        flags: target=auto
        fail_ci_if_error: true
        verbose: false
