name: Lint
on: [pull_request]
jobs:
  linter:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install modules
          run: yarn
        - name: Run ESLint
          run: eslint . --ext .ts --no-fix --max-warnings 0
