name: Issue automation

on:
  pull_request_review_comment: 
    types: [created]
jobs:
  notify_jira:
    runs-on: ubuntu-latest
    name: Notify Jira
    env:
      SELECTION: ${{ toJSON(secrets }}
    steps:
      - run: echo "${{ github.event.comment.body }}"
