name: Check Checkmarx Plugin Versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # every hour

jobs:
  check-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest versions from Open VSX
        run: |
          EXTENSIONS=("ast-results" "cx-dev-assist")

          for EXT in "${EXTENSIONS[@]}"; do
            URL="https://open-vsx.org/api/${EXT}"
            RESPONSE=$(curl -s $URL)
            VERSION=$(echo "$RESPONSE" | jq -r '.version')

            echo "=============================="
            echo "Extension: $EXT"
            echo "Latest Version: $VERSION"
          done
