name: Check Checkmarx Plugin Versions

on:
  workflow_dispatch:
  push:
    branches:
      - other/validate-plugin-version
  schedule:
    - cron: "0 * * * *"  # every hour

jobs:
  check-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest versions from Open VSX
        env:
          OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
        run: |
          EXTENSIONS=("ast-results" "cx-dev-assist")

          for EXT in "${EXTENSIONS[@]}"; do
            URL="https://open-vsx.org/api/${EXT}"

            if [ -n "$OPEN_VSX_TOKEN" ]; then
              RESPONSE=$(curl -s -H "Authorization: Bearer $OPEN_VSX_TOKEN" $URL)
            else
              RESPONSE=$(curl -s $URL)
            fi

            VERSION=$(echo "$RESPONSE" | jq -r '.version')

            echo "=============================="
            echo "Extension: $EXT"
            echo "Latest Version: $VERSION"
          done
